name: Build CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - release: latest
            shibboleth: ''
          - release: specific
            shibboleth: 3.2.3.1

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        env:
          _SHIBBOLETH_VERSION: ${{ matrix.shibboleth }}
        run: make ci
      - name: Check build artefacts
        run: ls -R build/
